projects/razor-pages/razor-pages-mvc/Controllers/EntryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PracticalAspNetCore.Data;
using System.Threading.Tasks;

namespace PracticalAspNetCore.Controllers
{
    [Route("Mvc")]
    public class EntryController : Controller
    {
        private GuestbookContext _db;

        public EntryController(GuestbookContext db) => _db = db;

        [Route("Index")]
        public async Task<IActionResult> Index()
        {
            var entries = await _db.Entries.AsNoTracking().ToListAsync();
            return View(entries);
        }

        [HttpPost]
        [Route("Edit")]
        public async Task<IActionResult> Edit(Entry entry)
        {
            if (!ModelState.IsValid) return View("Edit", entry);

            _db.Attach(entry).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Route("Edit")]
        public async Task<IActionResult> Edit(int id)
        {
            var entry = await _db.Entries.SingleOrDefaultAsync(e => e.Id == id);
            return View(entry);
        }

        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> Create(Entry entry)
        {
            if (!ModelState.IsValid) return View(entry);

            await _db.Entries.AddAsync(entry);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Route("Create")]
        public IActionResult Create() => View();

        [HttpPost]
        [Route("Like")]
        public async Task<IActionResult> Like(int id)
        {
            var entry = await _db.Entries.SingleOrDefaultAsync(e => e.Id == id);
            entry.Likes += 1;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

projects/razor-pages/razor-pages-mvc/Pages/RazorPages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PracticalAspNetCore.Data;
using System.Threading.Tasks;

namespace PracticalAspNetCore.Pages
{
    public class CreateModel : PageModel
    {
        private readonly GuestbookContext _db;

        public CreateModel(GuestbookContext db) => _db = db;

        [BindProperty]
        public Entry Entry { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            _db.Entries.Add(Entry);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

projects/razor-pages/razor-pages-mvc/Pages/RazorPages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PracticalAspNetCore.Data;
using Microsoft.EntityFrameworkCore;

namespace PracticalAspNetCore.Pages
{
    public class EditModel : PageModel
    {
        private readonly GuestbookContext _db;

        public EditModel(GuestbookContext db) => _db = db;

        [BindProperty]
        public Entry Entry { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Entry = await _db.Entries.FindAsync(id);

            if (Entry == null) return RedirectToPage("/Index");

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            _db.Attach(Entry).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

projects/razor-pages/razor-pages-mvc/Pages/RazorPages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PracticalAspNetCore.Data;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace PracticalAspNetCore.Pages
{
    public class IndexRazorPagesModel : PageModel
    {
        private readonly GuestbookContext _db;

        public IndexRazorPagesModel(GuestbookContext db) => _db = db;

        public IList<Entry> Entries { get; private set; }

        public async Task OnGetAsync()
        {
            Entries = await _db.Entries.AsNoTracking().ToListAsync();
        }

        public async Task<IActionResult> OnPostLikeAsync(int id)
        {
            var entry = await _db.Entries.FindAsync(id);
            entry.Likes += 1;
            await _db.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var entry = await _db.Entries.FindAsync(id);
            _db.Entries.Remove(entry);
            await _db.SaveChangesAsync();
            return RedirectToPage();
        }
    }
}

projects/razor-pages/razor-pages-mvc/Pages/Index.cshtml
@page
<h1>Welcome to Razor Pages and MVC example</h1>

<p>Go to <a href="RazorPages/Index">Razor Pages Implementation</a></p>

<p>Go to <a href="Mvc/Index">Mvc Implementation</a></p>

projects/razor-pages/razor-pages-mvc/Views/Entry/Create.cshtml
@model PracticalAspNetCore.Data.Entry
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html>
    <body>
        <p>
            Add new guestbook entry.
        </p>
        <div asp-validation-summary="All"></div>
        <form method="post" action="Create">
            <div>Name: <input asp-for="Content" /></div>
            <div>Email: <input asp-for="Email" /></div>
            <input type="submit" />
        </form>
    </body>
</html>

projects/razor-pages/razor-pages-mvc/Views/Entry/Edit.cshtml
@model PracticalAspNetCore.Data.Entry
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Edit Guestbook entry";
}

<h1>Edit Entry @Model.Id</h1>
<form method="post">
    <div asp-validation-summary="All"></div>
    <input asp-for="Id" type="hidden" />
    <input asp-for="Email" type="hidden" />
    <input asp-for="Likes" type="hidden" />
    <div>
        <label asp-for="Content"></label>
        <div>
            <input asp-for="Content" />
            <span asp-validation-for="Content"></span>
        </div>
    </div>

    <div>
        <button type="submit">Save</button>
    </div>
</form>

projects/razor-pages/razor-pages-mvc/Views/Entry/Index.cshtml
@model List<PracticalAspNetCore.Data.Entry>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<h1>MVC Implementation</h1>
<p>Add your entry to guestbook.</p>
<form method="post">
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Content</th>
            <th>Likes</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var entry in Model)
        {
            <tr>
                <td>@entry.Id</td>
                <td>@entry.Email</td>
                <td>@entry.Content</td>
                <td>@entry.Likes</td>
                <td>
                    <button type="submit" asp-controller="Entry" asp-action="Like" asp-route-id="@entry.Id">like</button>
                    <a asp-controller="Entry" asp-action="Edit" asp-route-id="@entry.Id">edit</a>
                </td>
            </tr>
        }
        </tbody>
    </table>

    <a asp-controller="Entry" asp-action="Create">Create</a>
</form>


<p>Go back to <a href="/Index">Index</a></p>